### PR TITLE
Blas: "completed"

### PR DESCRIPTION
**Pull request by tanguyl**
This follow up project aims to be a complete wrapper: all BLAS data types (single/double precision, complex numbers) and functions can be used.
However, to simplify the project, the previous higher level interface was dropped.
A small reference is provided to explain basic array manipulation; array shifting/copying is possible, but will need to be worked upon.

Finally, the testing is a bit limited: each function is tested once over correct inputs. Darwin/freebsd platforms are untested.

### CODE REVIEW

**Comment by dgud** [comment]
Isn't it better that I update my readme and point to your repository if someone stumbles upon my repo.
That way my repo can die in peace :-)

**Comment by tanguyl** [comment]
It is also a valid approach! 
However, since this update contains bits of your code and is by essence the same project, @peerst (which made the follow up possible) advocated to keep this repo as the main erlang BLAS wrapper.
In the end, this decision lies in your hand.

**Comment by dgud** [comment]
I think I would prefer that I have to much on my plate anyway, work, wx and wings.
And I don't think this have been used by anyone else than you, 
so I'm just glad I could inspire someone to pick up the torch.

So please feel free to update license to something else (preferably free) and remove my copyright.
And tell me which repo-link that I should point to.

**Comment by peerst** [comment]
Then I'd suggest we move it to EEF GitHub org and change the license to Apache 2.0

I'll take care of forking it in EEF GitHub and make Tanguy maintainer and maybe also you Dan (you can always ignore it)

**Comment by peerst** [comment]
Done: there is now https://github.com/erlef/blas

**Pull request closed without merging**
